# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-23 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
    ]
