# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-23 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankdetails', '0002_auto_20190823_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='ifsc',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
